- name: Install dependencies
  hosts: webservers

  tasks:
    # TODO: Insure docker and docker-compose are installed (this may also involve insuring pip is installed)
    - name: Configure max_map_count
      become: yes
      notify: Reboot
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        regexp: "^vm.max_map_count="
        line: "vm.max_map_count=262144"
  
  handlers:
    - name: Reboot
      become: yes
      reboot:

- name: Application files
  hosts: webservers
  
  tasks:
    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: civilstonks-elk
        state: absent

    - name: Insure civilstonks-elk directory exists
      ansible.builtin.file:
        path: ~/civilstonks-elk
        state: directory
        mode: '0755'

    - name: Copy over docker-compose file
      ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: ~/civilstonks-elk/docker-compose.yml

    - name: Create and start services
      community.docker.docker_compose:
        project_src: civilstonks-elk
        state: present
